server:
  port: 8086

#  ssl:
#    enabled-protocols: TLSv1.2,TLSv1.3
spring:
  data:
    redis:
      host: 127.0.0.1
      database: 0 # Redis数据库索引（默认为0）
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
  mvc:
    log-request-details: true
#  datasource:
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://192.168.8.2:1433;databaseName=generator_test000
#      username: sa
#      password: Aa123456
# 相关 数据库 连接配置 
mybatis:
  type-aliases-package: com.example.first_floor.generator.domain
  mapper-locations: classpath:/mapper/*.xml
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: root

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

